spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: username
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  port: 8080

